replicaCount: 1

image:
  name: snykbot
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

settingsFile: "/opt/settings.yaml"

secretSnykToken: ""
secretSlackAppToken: ""
secretSlackBotToken: ""

settingGroupId: ""
settingAllowDuplicateOrgNames: ""
settingBusinessUnitRegex: ""
settingTeamNameRegex: ""
settingCreateOrgCommand: ""
settingSsoName: ""
settingSsoSignInLink: ""