apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  settings.yaml: |
    # Where should the Slack bot get our Slack tokens from
    slack_bot_token_env_var_name: "SLACK_BOT_TOKEN"
    slack_app_token_env_var_name: "SLACK_APP_TOKEN"
    
    # Where should the Slack bot get your Snyk token from
    snyk_token_env_var_name: "SNYK_TOKEN"
    
    # The group we'll be placing new orgs under
    snyk_group_id: {{ .Values.settingGroupId }}
    
    # Multiple orgs with the same name are allowed in Snyk, but should the bot allow this?
    allow_duplicate_org_names: {{ .Values.settingAllowDuplicateOrgNames }}
    
    # Business unit must follow the regex pattern to be accepted
    business_unit_regex_pattern: {{ .Values.settingBusinessUnitRegex }}
    
    # Team name must follow the regex pattern to be accepted
    team_name_regex_pattern: {{ .Values.settingTeamNameRegex }}
    
    # The command to use for creating an org
    command_create_org: {{ .Values.settingCreateOrgCommand }}
    
    # The link we'll send users to, to log in to Snyk
    sso_sign_in_link: {{ .Values.settingSsoSignInLink }}
    
    # SSO provider name
    sso_provider_name: {{ .Values.settingSsoName }}