apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snyk-org-slackbot.fullname" . }}
  labels:
    {{- include "snyk-org-slackbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snyk-org-slackbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snyk-org-slackbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SETTINGS_FILE_PATH
              value: {{ .Values.settingsFile }}
            - name: SNYK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: SNYK_TOKEN
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: SLACK_BOT_TOKEN
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: SLACK_APP_TOKEN
          volumeMounts:
            - name: config
              mountPath: {{ .Values.settingsFile }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap