apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SNYK_TOKEN: {{ .Values.secretSnykToken | b64enc | quote }}
  SLACK_APP_TOKEN: {{ .Values.secretSlackAppToken | b64enc | quote }}
  SLACK_BOT_TOKEN: {{ .Values.secretSlackBotToken | b64enc | quote }}