name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker_build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image for scanning
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: ${{matrix.platform}}
          tags: ghcr.io/snyk-playground/snyk-org-slackbot:${{ github.sha }}
      - name: Snyk Container Test
        run: snyk container test ghcr.io/snyk-playground/snyk-org-slackbot:${{ github.sha }} --platform=${{matrix.platform}} --exclude-base-image-vulns --file=Dockerfile --org=ie-playground --severity-threshold=critical --project-lifecycle=development
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Container Monitor
        run: snyk container monitor ghcr.io/snyk-playground/snyk-org-slackbotc:$GITHUB_SHA --platform=${{matrix.platform}} --file=Dockerfile --org=ie-playground --project-lifecycle=development --tags=gitsha=$GITHUB_SHA,app=snyk-org-slackbot
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{matrix.platform}}
          push: true
          tags: |
            ghcr.io/snyk-playground/snyk-org-slackbot:latest
            ghcr.io/snyk-playground/snyk-org-slackbot:${{ github.sha }}
